/* GENERATED by scripts/extract-catalogues.mjs — do not edit by hand.
   Regenerate whenever a game adds or changes collectibles:

     node scripts/extract-catalogues.mjs --repos /path/to/checkouts

   This is what a child COULD collect. The hub needs it to show locked items
   with their hints; without that a collection page is just a receipt for what
   you already have. Paint is absent on purpose — its collectible is the
   child's own artwork, which cannot be enumerated in advance.

   Counts at generation time: PrataSala 12, KidlaTest 42, ENG-learning 26, Memory 5. */

export const CATALOGUES = {
  "PrataSala": {
    "cards": [
      {
        "id": "1",
        "name": "Pūķēns Dārcis",
        "art": {
          "type": "emoji",
          "value": "🐉"
        }
      },
      {
        "id": "2",
        "name": "Gudrā Pūce",
        "art": {
          "type": "emoji",
          "value": "🦉"
        }
      },
      {
        "id": "3",
        "name": "Salas Papagailis",
        "art": {
          "type": "emoji",
          "value": "🦜"
        }
      },
      {
        "id": "4",
        "name": "Jūras Bruņurupucis",
        "art": {
          "type": "emoji",
          "value": "🐢"
        }
      },
      {
        "id": "5",
        "name": "Zvaigžņu Krabis",
        "art": {
          "type": "emoji",
          "value": "🦀"
        }
      },
      {
        "id": "6",
        "name": "Varavīksnes Zivs",
        "art": {
          "type": "emoji",
          "value": "🐠"
        }
      },
      {
        "id": "7",
        "name": "Dārgumu Lāde",
        "art": {
          "type": "emoji",
          "value": "🧰"
        }
      },
      {
        "id": "8",
        "name": "Burvju Gliemežvāks",
        "art": {
          "type": "emoji",
          "value": "🐚"
        }
      },
      {
        "id": "9",
        "name": "Maģiskais Kokoss",
        "art": {
          "type": "emoji",
          "value": "🥥"
        }
      },
      {
        "id": "10",
        "name": "Salas Mērkaķis",
        "art": {
          "type": "emoji",
          "value": "🐵"
        }
      },
      {
        "id": "11",
        "name": "Vulkāna Akmens",
        "art": {
          "type": "emoji",
          "value": "🌋"
        }
      },
      {
        "id": "12",
        "name": "Rozā Flamingo",
        "art": {
          "type": "emoji",
          "value": "🦩"
        }
      }
    ]
  },
  "KidlaTest": {
    "cards": [
      {
        "id": "1",
        "name": "Ceļojuma kartīte 1",
        "unlock": {
          "kind": "chapterEnd",
          "endId": 10
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/01.png"
        }
      },
      {
        "id": "2",
        "name": "Ceļojuma kartīte 2",
        "unlock": {
          "kind": "chapterEnd",
          "endId": 20
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/02.png"
        }
      },
      {
        "id": "3",
        "name": "Ceļojuma kartīte 3",
        "unlock": {
          "kind": "chapterEnd",
          "endId": 30
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/03.png"
        }
      },
      {
        "id": "4",
        "name": "Ceļojuma kartīte 4",
        "unlock": {
          "kind": "chapterEnd",
          "endId": 40
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/04.png"
        }
      },
      {
        "id": "5",
        "name": "Ceļojuma kartīte 5",
        "unlock": {
          "kind": "chapterEnd",
          "endId": 50
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/05.png"
        }
      },
      {
        "id": "6",
        "name": "Ceļojuma kartīte 6",
        "unlock": {
          "kind": "chapterEnd",
          "endId": 60
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/06.png"
        }
      },
      {
        "id": "7",
        "name": "Ceļojuma kartīte 7",
        "unlock": {
          "kind": "chapterEnd",
          "endId": 70
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/07.png"
        }
      },
      {
        "id": "8",
        "name": "Ceļojuma kartīte 8",
        "unlock": {
          "kind": "chapterEnd",
          "endId": 80
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/08.png"
        }
      },
      {
        "id": "9",
        "name": "Ceļojuma kartīte 9",
        "unlock": {
          "kind": "chapterEnd",
          "endId": 90
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/09.png"
        }
      },
      {
        "id": "10",
        "name": "Ceļojuma kartīte 10",
        "unlock": {
          "kind": "chapterEnd",
          "endId": 100
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/10.png"
        }
      },
      {
        "id": "11",
        "name": "Ceļojuma kartīte 11",
        "unlock": {
          "kind": "chapterEnd",
          "endId": 106
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/11.png"
        }
      },
      {
        "id": "12",
        "name": "Sērijas kartīte 1",
        "hint": "10 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 1
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/12.png"
        }
      },
      {
        "id": "13",
        "name": "Sērijas kartīte 2",
        "hint": "20 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 2
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/13.png"
        }
      },
      {
        "id": "14",
        "name": "Sērijas kartīte 3",
        "hint": "30 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 3
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/14.png"
        }
      },
      {
        "id": "15",
        "name": "Sērijas kartīte 4",
        "hint": "40 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 4
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/15.png"
        }
      },
      {
        "id": "16",
        "name": "Sērijas kartīte 5",
        "hint": "50 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 5
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/16.png"
        }
      },
      {
        "id": "17",
        "name": "Sērijas kartīte 6",
        "hint": "60 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 6
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/17.png"
        }
      },
      {
        "id": "18",
        "name": "Sērijas kartīte 7",
        "hint": "70 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 7
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/18.png"
        }
      },
      {
        "id": "19",
        "name": "Sērijas kartīte 8",
        "hint": "80 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 8
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/19.png"
        }
      },
      {
        "id": "20",
        "name": "Sērijas kartīte 9",
        "hint": "90 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 9
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/20.png"
        }
      },
      {
        "id": "21",
        "name": "Sērijas kartīte 10",
        "hint": "100 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 10
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/21.png"
        }
      },
      {
        "id": "22",
        "name": "Sērijas kartīte 11",
        "hint": "110 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 11
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/22.png"
        }
      },
      {
        "id": "23",
        "name": "Sērijas kartīte 12",
        "hint": "120 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 12
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/23.png"
        }
      },
      {
        "id": "24",
        "name": "Sērijas kartīte 13",
        "hint": "130 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 13
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/24.png"
        }
      },
      {
        "id": "25",
        "name": "Sērijas kartīte 14",
        "hint": "140 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 14
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/25.png"
        }
      },
      {
        "id": "26",
        "name": "Sērijas kartīte 15",
        "hint": "150 vārdi pēc kārtas",
        "unlock": {
          "kind": "streak",
          "n": 15
        },
        "art": {
          "type": "img",
          "value": "/KidlaTest/images/milestones/26.png"
        }
      }
    ],
    "treasures": [
      {
        "id": "treasure-5",
        "name": "Lentīte",
        "art": {
          "type": "emoji",
          "value": "🎀"
        },
        "hint": "5 zvaigznes"
      },
      {
        "id": "treasure-12",
        "name": "Zvaigznīte",
        "art": {
          "type": "emoji",
          "value": "🌟"
        },
        "hint": "12 zvaigznes"
      },
      {
        "id": "treasure-20",
        "name": "Vienradzis",
        "art": {
          "type": "emoji",
          "value": "🦄"
        },
        "hint": "20 zvaigznes"
      },
      {
        "id": "treasure-30",
        "name": "Konfekte",
        "art": {
          "type": "emoji",
          "value": "🍭"
        },
        "hint": "30 zvaigznes"
      },
      {
        "id": "treasure-42",
        "name": "Kronis",
        "art": {
          "type": "emoji",
          "value": "👑"
        },
        "hint": "42 zvaigznes"
      },
      {
        "id": "treasure-55",
        "name": "Spārni",
        "art": {
          "type": "emoji",
          "value": "🧚"
        },
        "hint": "55 zvaigznes"
      },
      {
        "id": "treasure-70",
        "name": "Varavīksne",
        "art": {
          "type": "emoji",
          "value": "🌈"
        },
        "hint": "70 zvaigznes"
      },
      {
        "id": "treasure-88",
        "name": "Dāvana",
        "art": {
          "type": "emoji",
          "value": "🎁"
        },
        "hint": "88 zvaigznes"
      },
      {
        "id": "treasure-105",
        "name": "Dārgakmens",
        "art": {
          "type": "emoji",
          "value": "💎"
        },
        "hint": "105 zvaigznes"
      },
      {
        "id": "treasure-125",
        "name": "Pils",
        "art": {
          "type": "emoji",
          "value": "🏰"
        },
        "hint": "125 zvaigznes"
      },
      {
        "id": "treasure-150",
        "name": "Kauss",
        "art": {
          "type": "emoji",
          "value": "🏆"
        },
        "hint": "150 zvaigznes"
      },
      {
        "id": "treasure-180",
        "name": "Balons",
        "art": {
          "type": "emoji",
          "value": "🎈"
        },
        "hint": "180 zvaigznes"
      },
      {
        "id": "treasure-215",
        "name": "Gaisa pūķis",
        "art": {
          "type": "emoji",
          "value": "🪁"
        },
        "hint": "215 zvaigznes"
      },
      {
        "id": "treasure-255",
        "name": "Saulespuķe",
        "art": {
          "type": "emoji",
          "value": "🌻"
        },
        "hint": "255 zvaigznes"
      },
      {
        "id": "treasure-295",
        "name": "Rakete",
        "art": {
          "type": "emoji",
          "value": "🚀"
        },
        "hint": "295 zvaigznes"
      },
      {
        "id": "treasure-335",
        "name": "Medaļa",
        "art": {
          "type": "emoji",
          "value": "🏅"
        },
        "hint": "335 zvaigznes"
      }
    ]
  },
  "ENG-learning": {
    "cards": [
      {
        "id": "first_session",
        "name": "Pirmais solis",
        "hint": "Nospēlē pirmo spēli",
        "tier": "bronze",
        "art": {
          "type": "emoji",
          "value": "🌱"
        }
      },
      {
        "id": "first_word",
        "name": "Pirmais vārds",
        "hint": "Apgūsti savu pirmo vārdu",
        "tier": "bronze",
        "art": {
          "type": "emoji",
          "value": "🔤"
        }
      },
      {
        "id": "streak_3",
        "name": "Trīs dienas",
        "hint": "Spēlē trīs dienas pēc kārtas",
        "tier": "bronze",
        "art": {
          "type": "emoji",
          "value": "🔥"
        }
      },
      {
        "id": "streak_7",
        "name": "Vesela nedēļa",
        "hint": "Spēlē septiņas dienas pēc kārtas",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "🔥"
        }
      },
      {
        "id": "streak_14",
        "name": "Divas nedēļas",
        "hint": "Spēlē četrpadsmit dienas pēc kārtas",
        "tier": "gold",
        "art": {
          "type": "emoji",
          "value": "🔥"
        }
      },
      {
        "id": "streak_30",
        "name": "Vesels mēnesis!",
        "hint": "Spēlē trīsdesmit dienas pēc kārtas",
        "tier": "rainbow",
        "art": {
          "type": "emoji",
          "value": "🏆"
        }
      },
      {
        "id": "words_10",
        "name": "Desmit vārdi",
        "hint": "Apgūsti 10 vārdus",
        "tier": "bronze",
        "art": {
          "type": "emoji",
          "value": "⭐"
        }
      },
      {
        "id": "words_25",
        "name": "Divdesmit pieci",
        "hint": "Apgūsti 25 vārdus",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "🌟"
        }
      },
      {
        "id": "words_50",
        "name": "Piecdesmit vārdi",
        "hint": "Apgūsti 50 vārdus",
        "tier": "gold",
        "art": {
          "type": "emoji",
          "value": "💫"
        }
      },
      {
        "id": "words_100",
        "name": "Simts vārdu!",
        "hint": "Apgūsti 100 vārdus",
        "tier": "rainbow",
        "art": {
          "type": "emoji",
          "value": "👑"
        }
      },
      {
        "id": "unit_animals",
        "name": "Dzīvnieku draugs",
        "hint": "Apgūsti visu tēmu “Dzīvnieki”",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "🐶"
        }
      },
      {
        "id": "unit_food",
        "name": "Garšu pazinējs",
        "hint": "Apgūsti visu tēmu “Ēdiens”",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "🍎"
        }
      },
      {
        "id": "unit_colors",
        "name": "Krāsu mākslinieks",
        "hint": "Apgūsti visu tēmu “Krāsas”",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "🎨"
        }
      },
      {
        "id": "unit_body",
        "name": "No galvas līdz kājām",
        "hint": "Apgūsti visu tēmu “Ķermenis”",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "👀"
        }
      },
      {
        "id": "unit_family",
        "name": "Ģimenes sirds",
        "hint": "Apgūsti visu tēmu “Ģimene”",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "👨‍👩‍👧"
        }
      },
      {
        "id": "unit_numbers",
        "name": "Skaitļu meistars",
        "hint": "Apgūsti visu tēmu “Skaitļi”",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "🔢"
        }
      },
      {
        "id": "units_5",
        "name": "Piecas tēmas",
        "hint": "Pabeidz piecas tēmas",
        "tier": "gold",
        "art": {
          "type": "emoji",
          "value": "🗺️"
        }
      },
      {
        "id": "sessions_10",
        "name": "Desmit spēles",
        "hint": "Nospēlē 10 spēles",
        "tier": "bronze",
        "art": {
          "type": "emoji",
          "value": "🎯"
        }
      },
      {
        "id": "sessions_25",
        "name": "Divdesmit piecas spēles",
        "hint": "Nospēlē 25 spēles",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "🚀"
        }
      },
      {
        "id": "sessions_50",
        "name": "Piecdesmit spēles",
        "hint": "Nospēlē 50 spēles",
        "tier": "gold",
        "art": {
          "type": "emoji",
          "value": "🎖️"
        }
      },
      {
        "id": "perfect_round",
        "name": "Bez kļūdām",
        "hint": "Nospēlē spēli bez nevienas kļūdas",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "💯"
        }
      },
      {
        "id": "busy_week",
        "name": "Čakla nedēļa",
        "hint": "Nospēlē piecas spēles vienā nedēļā",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "📅"
        }
      },
      {
        "id": "first_sentence",
        "name": "Pirmais teikums",
        "hint": "Pabeidz savu pirmo teikumu",
        "tier": "silver",
        "art": {
          "type": "emoji",
          "value": "💬"
        }
      },
      {
        "id": "first_phonics",
        "name": "Burtu draugs",
        "hint": "Uzmini vārdu pēc pirmā burta",
        "tier": "bronze",
        "art": {
          "type": "emoji",
          "value": "🅰️"
        }
      },
      {
        "id": "first_memory",
        "name": "Laba atmiņa",
        "hint": "Atrodi visus pārīšus",
        "tier": "bronze",
        "art": {
          "type": "emoji",
          "value": "🃏"
        }
      },
      {
        "id": "explorer",
        "name": "Pētnieks",
        "hint": "Izmēģini visu veidu uzdevumus",
        "tier": "gold",
        "art": {
          "type": "emoji",
          "value": "🧭"
        }
      }
    ]
  },
  "Memory": {
    "games": [
      {
        "id": "dots",
        "name": "Mazo punktu pāri"
      },
      {
        "id": "count",
        "name": "Saskaiti un ieliec"
      },
      {
        "id": "bigger",
        "name": "Lielākais uzvar"
      },
      {
        "id": "path",
        "name": "Lēc pa skaitļu taku"
      },
      {
        "id": "market",
        "name": "Atmiņas tirgus"
      }
    ]
  }
};
